// react-client/src/pages/home/mycard/card2/MyCard.tsx
import React from 'react';
import MyCardText from './MyCardText';
import styles from '../../card/Card.module.css';

const MyCard: React.FC = () => {
  return (
    <div className={styles.card}>
      <div className={styles.id}>#0</div>
      <div className={styles.title}>Lorem ipsum</div>
      <div className={styles.text}>
        <MyCardText></MyCardText>
      </div>
      <div className={styles.operation}>
        <div className={styles.id}></div>
        <div className={styles.link}>
          <a href="url">link</a>
        </div>
        <div className={styles.diagram}>
          <a href="url">diagram</a>
        </div>
      </div>
    </div>
  );
};

export default MyCard;

// sentence-diagram-client/src/components/MyCard.vue
<template>
  <div class="card">
    <div class="card-id">#0</div>
    <div class="card-title">Lorem ipsum</div>
    <div class="card-text" id="app-1">
      <my-card-text></my-card-text>
    </div>
    <div class="card-operation">
      <a href="http://localhost:8080/">Link</a>
    </div>
  </div>
</template>

<script>
import Vue from 'vue';
import MyCardText from './MyCardText.vue';

Vue.component('my-card-text', MyCardText);

export default {};
</script>
