// react-client/src/pages/home/mycard/MyCard.tsx
import React from 'react';
import MyCardText from './text/MyCardText';

const MyCard = () => {
  return (
    <div className="card">
      <div className="card-id">#0</div>
      <div className="card-title">Lorem ipsum</div>
      <div className="card-text">
        <MyCardText></MyCardText>
      </div>
      <div className="card-operation">
        <div className="card-id"></div>
        <div className="card-link">
          <a href="url">link</a>
        </div>
        <div className="card-diagram">
          <a href="url">diagram</a>
        </div>
      </div>
    </div>
  );
};

export default MyCard;

// sentence-diagram-client/src/components/MyCard.vue
<template>
  <div class="card">
    <div class="card-id">#0</div>
    <div class="card-title">Lorem ipsum</div>
    <div class="card-text" id="app-1">
      <my-card-text></my-card-text>
    </div>
    <div class="card-operation">
      <a href="http://localhost:8080/">Link</a>
    </div>
  </div>
</template>

<script>
import Vue from 'vue';
import MyCardText from './MyCardText.vue';

Vue.component('my-card-text', MyCardText);

export default {};
</script>
