// vue-client/src/components/MyCard.vue
<template>
  <div class="card">
    <div class="card-id">#0</div>
    <div class="card-title">Lorem ipsum</div>
    <div class="card-text" id="app-2">
      <my-card-text></my-card-text>
    </div>
    <div class="card-operation">
      <div class="card-id">#{{id}}</div>
      <div class="card-link">
        <a :href="url">link</a>
      </div>
      <div class="card-diagram">
        <a v-on:click="showDiagram">
          diagram
          <i class="fas fa-pencil-ruler"></i>
        </a>
      </div>
    </div>
  </div>
</template>

<script>
import Vue from 'vue';
import MyCardText from './MyCardText.vue';

Vue.component('my-card-text', MyCardText);

export default {
  props: {
    id: Number,
    title: String,
    text: String,
    url: String
  },
  methods: {
    showDiagram: function() {
      let id = 99;
      let title = 'sample title';
      let text = 'The white unicorn flew.';
      let jsonStr =
        '[{"vnodes":[{"ids":"1","text":"The"},{"ids":"2","text":"white"},{"ids":"3","text":"unicorn"},{"ids":"4","text":"flew"}],"vedges":[{"fromIds":"1","toIds":"3","type":"mod"},{"fromIds":"2","toIds":"3","type":"mod"},{"fromIds":"4","toIds":"3","type":"subj"}]}]';
      let diagramData = JSON.parse(jsonStr);
      console.dir(diagramData);
      // イベント発行
      this.$emit('show-diagram', { id, title, text, diagramData });
    }
  }
};
</script>

// react-client/src/pages/home/mycard/MyCard.tsx
import React from 'react';
import MyCardText from './text/MyCardText';

const MyCard = () => {
  return (
    <div className="card">
      <div className="card-id">#0</div>
      <div className="card-title">Lorem ipsum</div>
      <div className="card-text">
        <MyCardText></MyCardText>
      </div>
      <div className="card-operation">
        <div className="card-id"></div>
        <div className="card-link">
          <a href="url">link</a>
        </div>
        <div className="card-diagram">
          <a href="url">diagram</a>
        </div>
      </div>
    </div>
  );
};

export default MyCard;
